### PR TITLE
[SYCL] Upstream Merge and test suite fixes

### PR DESCRIPTION
**Pull request by Ralender**
Merge https://github.com/intel/llvm into sycl/unified/next
Resolve conflicts
Fixes falling tests

### CODE REVIEW

**Comment by keryell** [comment]
Thank you for looking at this.
It looks like a lot of stuff changed and my old build documentation does not work anymore.
Which recipe do you apply to build everything?
I have applied the recipe from https://intel.github.io/llvm-docs/GetStartedGuide.html but it fails towards the end:
```
python $SYCL_HOME/buildbot/configure.py
python $SYCL_HOME/buildbot/compile.py



[2337/2489] Building CXX object tools/sycl/source/CMakeFiles/sycl_object.dir/backend/opencl.cpp.o
FAILED: tools/sycl/source/CMakeFiles/sycl_object.dir/backend/opencl.cpp.o 
/usr/bin/c++  -DCL_TARGET_OPENCL_VERSION=220 -DXPTI_ENABLE_INSTRUMENTATION -DXPTI_STATIC_LIBRARY -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/sycl/source -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source -I/usr/include/libxml2 -Iinclude -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/llvm/include -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/xpti/include -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include -Itools/sycl/OpenCL/inc -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wextra -Wno-deprecated-declarations -Werror -O3    -UNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -std=c++2a -MD -MT tools/sycl/source/CMakeFiles/sycl_object.dir/backend/opencl.cpp.o -MF tools/sycl/source/CMakeFiles/sycl_object.dir/backend/opencl.cpp.o.d -o tools/sycl/source/CMakeFiles/sycl_object.dir/backend/opencl.cpp.o -c /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source/backend/opencl.cpp
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl.hpp:22,
                 from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source/backend/opencl.cpp:9:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp: In lambda function:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:572:57: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
  572 |                                     IsPHSrc, IsPHDst>> ([=]() {
      |                                                         ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:572:57: note: add explicit ‘this’ or ‘*this’ capture
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp: In lambda function:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:611:10: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
  611 |         ([=]() {
      |          ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:611:10: note: add explicit ‘this’ or ‘*this’ capture
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp: In lambda function:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:647:10: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
  647 |         ([=]() {
      |          ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:647:10: note: add explicit ‘this’ or ‘*this’ capture
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga.hpp:19,
                 from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl.hpp:48,
                 from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source/backend/opencl.cpp:9:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga/partition_array.hpp: At global scope:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga/partition_array.hpp:178:3: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  178 |   const iterator begin() const { return elems; }
      |   ^~~~~
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga/partition_array.hpp:180:3: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  180 |   const iterator end() const { return elems+Size; }
      |   ^~~~~
cc1plus: all warnings being treated as errors
[2338/2489] Building CXX object tools/sycl/source/CMakeFiles/sycl_object.dir/backend/level_zero.cpp.o
FAILED: tools/sycl/source/CMakeFiles/sycl_object.dir/backend/level_zero.cpp.o 
/usr/bin/c++  -DCL_TARGET_OPENCL_VERSION=220 -DXPTI_ENABLE_INSTRUMENTATION -DXPTI_STATIC_LIBRARY -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/sycl/source -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source -I/usr/include/libxml2 -Iinclude -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/llvm/include -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/xpti/include -I/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include -Itools/sycl/OpenCL/inc -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wextra -Wno-deprecated-declarations -Werror -O3    -UNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -std=c++2a -MD -MT tools/sycl/source/CMakeFiles/sycl_object.dir/backend/level_zero.cpp.o -MF tools/sycl/source/CMakeFiles/sycl_object.dir/backend/level_zero.cpp.o.d -o tools/sycl/source/CMakeFiles/sycl_object.dir/backend/level_zero.cpp.o -c /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source/backend/level_zero.cpp
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl.hpp:22,
                 from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source/backend/level_zero.cpp:9:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp: In lambda function:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:572:57: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
  572 |                                     IsPHSrc, IsPHDst>> ([=]() {
      |                                                         ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:572:57: note: add explicit ‘this’ or ‘*this’ capture
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp: In lambda function:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:611:10: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
  611 |         ([=]() {
      |          ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:611:10: note: add explicit ‘this’ or ‘*this’ capture
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp: In lambda function:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:647:10: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
  647 |         ([=]() {
      |          ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/handler.hpp:647:10: note: add explicit ‘this’ or ‘*this’ capture
In file included from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga.hpp:19,
                 from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl.hpp:48,
                 from /home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/source/backend/level_zero.cpp:9:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga/partition_array.hpp: At global scope:
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga/partition_array.hpp:178:3: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  178 |   const iterator begin() const { return elems; }
      |   ^~~~~
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/sycl/include/CL/sycl/xilinx/fpga/partition_array.hpp:180:3: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  180 |   const iterator end() const { return elems+Size; }
      |   ^~~~~
cc1plus: all warnings being treated as errors
[2348/2489] Building CXX object tools/sycl/source/CMakeFiles/sycl_object.dir/detail/builtins_math.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/buildbot/compile.py", line 63, in <module>
    ret = main()
  File "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/buildbot/compile.py", line 59, in main
    return do_compile(args)
  File "/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/buildbot/compile.py", line 37, in do_compile
    subprocess.check_call(cmake_cmd, cwd=abs_obj_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/llvm/build', '--', 'deploy-sycl-toolchain', 'deploy-opencl-aot', '-j', '12']' returned non-zero exit status 1.
-<rkeryell@rk-xsj:~/Xilinx/Projects/LLVM/worktrees/xilinx/build [master]>-               
```
So it looks like it is mostly due to the C++20 deprecation on my system with g++ 9.3.0

**Comment by keryell** [comment]
I also tried the build recipe you sent me by e-mail with various compiler combinations.
Are you sure you correctly merged the link requirement of the triSYCL LLVM passes?
We have been  lazy there by using Boost... :-)
```
FAILED: lib/libLLVMInSPIRation.so.11git 
: && /usr/bin/c++ -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -march=native  -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/build-Release/./lib  -Wl,-O3 -Wl,--gc-sections -shared -Wl,-soname,libLLVMInSPIRation.so.11git -o lib/libLLVMInSPIRation.so.11git lib/SYCL/InSPIRation/CMakeFiles/LLVMInSPIRation.dir/InSPIRation.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMTransformUtils.so.11git  lib/libLLVMCore.so.11git  lib/libLLVMSupport.so.11git  lib/libLLVMDemangle.so.11git  -Wl,-rpath-link,/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/build-Release/lib && :
/usr/bin/ld: lib/SYCL/InSPIRation/CMakeFiles/LLVMInSPIRation.dir/InSPIRation.cpp.o: in function `(anonymous namespace)::InSPIRation::runOnModule(llvm::Module&)':
InSPIRation.cpp:(.text._ZN12_GLOBAL__N_111InSPIRation11runOnModuleERN4llvm6ModuleE+0x207b): undefined reference to `boost::throw_exception(std::exception const&, boost::source_location const&)'
collect2: error: ld returned 1 exit status
```

**Comment by agozillon** [comment]
> I also tried the build recipe you sent me by e-mail with various compiler combinations.
> Are you sure you correctly merged the link requirement of the triSYCL LLVM passes?
> We have been lazy there by using Boost... :-)
> 
> ```
> FAILED: lib/libLLVMInSPIRation.so.11git 
> : && /usr/bin/c++ -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -march=native  -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/build-Release/./lib  -Wl,-O3 -Wl,--gc-sections -shared -Wl,-soname,libLLVMInSPIRation.so.11git -o lib/libLLVMInSPIRation.so.11git lib/SYCL/InSPIRation/CMakeFiles/LLVMInSPIRation.dir/InSPIRation.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMTransformUtils.so.11git  lib/libLLVMCore.so.11git  lib/libLLVMSupport.so.11git  lib/libLLVMDemangle.so.11git  -Wl,-rpath-link,/home/rkeryell/Xilinx/Projects/LLVM/worktrees/xilinx/build-Release/lib && :
> /usr/bin/ld: lib/SYCL/InSPIRation/CMakeFiles/LLVMInSPIRation.dir/InSPIRation.cpp.o: in function `(anonymous namespace)::InSPIRation::runOnModule(llvm::Module&)':
> InSPIRation.cpp:(.text._ZN12_GLOBAL__N_111InSPIRation11runOnModuleERN4llvm6ModuleE+0x207b): undefined reference to `boost::throw_exception(std::exception const&, boost::source_location const&)'
> collect2: error: ld returned 1 exit status
> ```

No, we never linked against boost and still don't there is a TODO for that here: 

https://github.com/triSYCL/sycl/blob/sycl/unified/master/llvm/lib/SYCL/InSPIRation/InSPIRation.cpp#L40

I'm still a little unclear where boost is getting linked in for us, but it'll pick it up in the environment. 

Modifying the CMake appropriately to link boost for our passes is a good idea, in-case where-ever/however we're picking up boost from as a link argument gets altered.

What's more likely is that your running a newer version of boost than @Ralender and they added a new boost::throw_exception overload which takes a boost::source_location const& as a second parameter! Which will in turn cause boost to complain as we've only defined the old overload here:

https://github.com/triSYCL/sycl/blob/sycl/unified/master/llvm/lib/SYCL/InSPIRation/InSPIRation.cpp#L50

if BOOST_NO_EXCEPTIONS is defined: 

https://github.com/triSYCL/sycl/blob/sycl/unified/master/llvm/lib/SYCL/InSPIRation/InSPIRation.cpp#L38

Then boost only declares the function but gives it no definition, I unfortunately can't exactly remember why I decided to go with no exceptions. I think it might have been because it's possible to turn off assertions in Clang/LLVM which can cause some issues. It's been a while though so perhaps it could do with a reinvestigation! 

Hopefully a little helpful.

**Comment by keryell** [comment]
@agozillon thanks for the deep analysis.
I completely forgot about this Boost stuff.
Adding some Boost-like implementation in our code does not seems to be scalable neither portable compare to just using Boost and link with the library as it is required.
For `BOOST_NO_EXCEPTIONS` I do not remember whether Clang/LLVM is compiled with no exception mode...
On the short term I guess the reasonable solution here is to add the missing overload you suggest to https://github.com/triSYCL/sycl/blob/sycl/unified/master/llvm/lib/SYCL/InSPIRation/InSPIRation.cpp since the role of this PR is just trying to catch up with latest DPC++ version without changing fundamental things.

**Comment by Ralender** [comment]
`What's more likely is that your running a newer version of boost than @Ralender and they added a new boost::throw_exception overload which takes a boost::source_location const& as a second parameter!`
this was the issue.

from boost's release log this new parameter has been added in 1.73, the latest version.
i added a commit to the PR to provide or not the extra argument based on the boost version
@keryell can you try with this fix.

the default setting to build clang is no exception, i expect most of clang/llvm code isn't exception safe so disabling exception is a good thing.

**Comment by agozillon** [comment]
No problem, more than happy to help! And yes, you are both correct it was likely because of the no exception build option of Clang. 

And I agree continuing to use Boost is a good idea, we use some functionality that would be a bit painful/unnecessary to recreate on our own... SHA(5?), de-mangling etc.

**Comment by keryell** [comment]
> And I agree continuing to use Boost is a good idea, we use some functionality that would be a bit painful/unnecessary to recreate on our own... SHA(5?), de-mangling etc.

Yes I agree. triSYCL is a research project for now, so it does not make sense to use old C++14 and no external library as it would be the case for up-streaming today.

**Comment by keryell** [comment]
I love the summary of this PR: *Ralender wants to merge 10,000 commits*. Ten thousands commits, what a shower! :-)

**Comment by keryell** [comment]
Thank you for the great work!

**Pull request merged**
